local _, ns = ...

ns.addGuide({
    key = "alchemy", name = "Alchemy", kind = "Primary crafting",
    summary = "WoW-Professions Classic route from 1-300 using the listed potion and elixir breakpoints.",
    tips = {
        "Alchemy pairs with Herbalism to reduce Auction House cost.",
        "Buy Recipe: Superior Mana Potion while near Darnassus or Undercity; it is needed at 265.",
        "Buy Recipe: Major Healing Potion from Evie Whirlbrew in Everlook before the final stretch.",
    },
    shopping = {
        "65 Peacebloom, 65 Silverleaf, 85 Empty Vial",
        "100 Briarthorn, 35 Bruiseweed, 105 Leaded Vial",
        "20 Mageroyal, 50 Stranglekelp, 35 Liferoot, 35 Kingsblood",
        "35 Goldthorn, 5 Wild Steelbloom, 75 Sungrass, 15 Khadgar's Whisker",
        "120 Crystal Vial, 45 Arthas' Tears, 60 Blindweed",
        "75 Golden Sansam, 20 Mountain Silversage",
    },
    steps = {
        { "1-60", "65x Minor Healing Potion", "65 Peacebloom, 65 Silverleaf, 65 Empty Vial", "Trainer", "Keep the potions; Lesser Healing Potion uses them next." },
        { "60-110", "65x Lesser Healing Potion", "65 Minor Healing Potion, 65 Briarthorn", "Trainer", "Train Journeyman before the 75 cap." },
        { "110-140", "35x Healing Potion", "35 Bruiseweed, 35 Briarthorn, 35 Leaded Vial", "Trainer", "Expert Alchemy is needed past 150." },
        { "140-155", "20x Lesser Mana Potion", "20 Mageroyal, 20 Stranglekelp, 20 Empty Vial", "Trainer", "Yellow for the last points; Fire Oil or more Healing Potion can bridge." },
        { "155-185", "35x Greater Healing Potion", "35 Liferoot, 35 Kingsblood, 35 Leaded Vial", "Trainer", "If you made Fire Oil, Elixir of Firepower is an option." },
        { "185-210", "30x Elixir of Agility", "30 Stranglekelp, 30 Goldthorn, 30 Leaded Vial", "Trainer", "Mana Potion, Lesser Invisibility Potion, or Nature Protection Potion can cover scarce Goldthorn." },
        { "210-215", "5x Elixir of Greater Defense", "5 Wild Steelbloom, 5 Goldthorn, 5 Leaded Vial", "Trainer", "Train Artisan before 225." },
        { "215-230", "15x Superior Healing Potion", "15 Sungrass, 15 Khadgar's Whisker, 15 Crystal Vial", "Trainer", "Short bridge into the Undead detection recipe." },
        { "230-265", "45x Elixir of Detect Undead", "45 Arthas' Tears, 45 Crystal Vial", "Trainer", "Main mid-Artisan push." },
        { "265-285", "30x Superior Mana Potion", "60 Sungrass, 60 Blindweed, 30 Crystal Vial", "Limited vendor recipe", "Recipe sold by Ulthir in Darnassus and Algernon in Undercity." },
        { "285-300", "20x Major Healing Potion", "40 Golden Sansam, 20 Mountain Silversage, 20 Crystal Vial", "Limited vendor recipe", "Recipe sold by Evie Whirlbrew in Everlook." },
    },
})

ns.addGuide({
    key = "blacksmithing", name = "Blacksmithing", kind = "Primary crafting",
    summary = "WoW-Professions Classic route through stones, rods, iron, mithril, and Imperial Plate.",
    tips = {
        "Pair with Mining if you want to farm the ore and stone.",
        "Save Rough, Coarse, Heavy, and Solid Grinding Stones when the route says to keep them.",
        "Plans: Mithril Spurs makes 235-270 much cheaper if you can buy it from the Auction House.",
    },
    shopping = {
        "150 Rough Stone, 95 Coarse Stone, 140 Copper Bar",
        "5 Silver Bar, 140 Bronze Bar, 105 Heavy Stone, 5 Gold Bar",
        "230 Iron Bar, 35 Green Dye, 190 Steel Bar",
        "480 Solid Stone if using Mithril Spurs, 20 Dense Stone",
        "220 Mithril Bar, 60 Mageweave Cloth",
        "730 Thorium Bar, 30 Star Ruby, 5 Aquamarine",
    },
    steps = {
        { "1-30", "40x Rough Sharpening Stone", "40 Rough Stone", "Trainer", "Cheap opener." },
        { "30-65", "55x Rough Grinding Stone", "110 Rough Stone", "Trainer", "Save 10 Rough Grinding Stones." },
        { "65-75", "25x Coarse Sharpening Stone", "25 Coarse Stone", "Trainer", "Train Journeyman before the 75 cap." },
        { "75-90", "35x Coarse Grinding Stone", "70 Coarse Stone", "Trainer", "Save the Coarse Grinding Stones." },
        { "90-100", "10x Runed Copper Belt", "100 Copper Bar", "Trainer", "Make extra if the Silver Rod step is expensive." },
        { "100-105", "5x Silver Rod", "5 Silver Bar, 10 Rough Grinding Stone", "Trainer", "Can be skipped with more Runed Copper Belts." },
        { "105-110", "5x Runed Copper Belt", "50 Copper Bar", "Trainer", "Short copper bridge." },
        { "110-125", "15x Rough Bronze Leggings", "90 Bronze Bar", "Trainer", "Train Expert before 150." },
        { "125-140", "35x Heavy Grinding Stone", "105 Heavy Stone", "Trainer", "Keep the Heavy Grinding Stones; continue to 150 if Heavy Stone is cheap." },
        { "140-150", "10x Patterned Bronze Bracers", "50 Bronze Bar, 20 Coarse Grinding Stone", "Trainer", "Uses the stones saved earlier." },
        { "150-155", "5x Golden Rod", "5 Gold Bar, 10 Coarse Grinding Stone", "Trainer", "Green Dye is sold by Tailoring and Leatherworking supply vendors." },
        { "155-165", "10x Green Iron Leggings", "80 Iron Bar, 10 Heavy Grinding Stone, 10 Green Dye", "Trainer", "Start using saved Heavy Grinding Stones." },
        { "165-190", "25x Green Iron Bracers", "150 Iron Bar, 25 Green Dye", "Trainer", "Reliable iron stretch." },
        { "190-200", "10x Golden Scale Bracers", "50 Steel Bar, 20 Heavy Grinding Stone", "Trainer", "Alliance Armorsmiths may want to keep 6." },
        { "200-210", "30x Solid Grinding Stone", "120 Solid Stone", "Trainer", "Keep at least 10; keep all if using Mithril Spurs." },
        { "210-225", "15x Heavy Mithril Gauntlet", "90 Mithril Bar, 60 Mageweave Cloth", "Trainer", "Train Artisan from Brikk Keencraft in Booty Bay before 225." },
        { "225-235", "10x Steel Plate Helm", "140 Steel Bar, 10 Solid Grinding Stone", "Trainer", "Horde Armorsmiths may want to keep 4." },
        { "235-250", "15x Mithril Spurs", "60 Mithril Bar, 45 Solid Grinding Stone", "Auction House plan", "Alternative: 15x Mithril Coif with 150 Mithril Bar and 90 Mageweave Cloth." },
        { "250-260", "20x Dense Sharpening Stone", "20 Dense Stone", "Trainer", "Simple Dense Stone step." },
        { "260-270", "20x Mithril Spurs", "80 Mithril Bar, 60 Solid Grinding Stone", "Auction House plan", "Alternatives: Thorium Bracers, Thorium Belt, Radiant Belt, Heavy Mithril Boots, or Imperial Plate Belt." },
        { "270-295", "25x Imperial Plate Bracers", "500 Thorium Bar, 25 Star Ruby", "Derotain Mudsipper quest", "Quest requires Thorium Bars in Tanaris; recipe turns yellow near the end." },
        { "295-300", "5x Imperial Plate Boots", "170 Thorium Bar, 5 Star Ruby, 5 Aquamarine", "Derotain Mudsipper quest", "Final Imperial Plate craft." },
    },
})

ns.addGuide({
    key = "enchanting", name = "Enchanting", kind = "Primary crafting",
    summary = "WoW-Professions Classic dust-efficient route with each required runed rod.",
    tips = {
        "Tailoring pairs well because crafted cloth greens can be disenchanted.",
        "Buy the Stonetalon/Ashenvale limited recipes before the 110-135 and 156-185 steps.",
        "Annora in Uldaman is required for Artisan and key 225+ recipes.",
    },
    shopping = {
        "125 Strange Dust, 1 Lesser Magic Essence, 12 Greater Magic Essence",
        "25 Lesser Astral Essence, 130 Soul Dust, 2 Greater Astral Essence",
        "250 Vision Dust, 2 Greater Mystic Essence, 5 Lesser Nether Essence",
        "360 Dream Dust, 40 Purple Lotus, 40 Illusion Dust",
        "4 Greater Eternal Essence, 4 Small Brilliant Shard, 2 Large Brilliant Shard",
        "Silver Rod, Shadowgem, Golden Rod, Iridescent Pearl, Truesilver Rod, Black Pearl, Arcanite Rod, Golden Pearl",
    },
    steps = {
        { "1-2", "1x Runed Copper Rod", "Copper Rod, Strange Dust, Lesser Magic Essence", "Trainer", "Copper Rod is sold by trade/enchanting supply vendors." },
        { "2-50", "Disenchant greens or 48x Bracer: Minor Health", "48 Strange Dust if crafting", "Trainer", "Disenchanting can cover much of this stretch." },
        { "50-90", "40x Enchant Bracer: Minor Health", "40 Strange Dust", "Trainer", "Can continue to 120 if Strange Dust is cheap." },
        { "90-100", "10x Enchant Bracer: Minor Stamina", "30 Strange Dust", "Trainer", "Train Journeyman before 75 cap." },
        { "100-101", "1x Runed Silver Rod", "Silver Rod, 6 Strange Dust, 3 Greater Magic Essence, Shadowgem", "Trainer", "Required rod upgrade." },
        { "101-110", "9x Greater Magic Wand", "9 Simple Wood, 9 Greater Magic Essence", "Trainer", "Short bridge before limited recipes." },
        { "110-135", "25x Enchant Cloak: Minor Agility", "25 Lesser Astral Essence", "Limited vendor formula", "Buy this and Bracer: Lesser Strength from Kulwia or Dalria." },
        { "135-155", "20x Enchant Bracer: Lesser Stamina", "40 Soul Dust", "Expert trainer", "Expert trainers are Kitta Firewind and Hgarth." },
        { "155-156", "1x Runed Golden Rod", "Golden Rod, Iridescent Pearl, 2 Greater Astral Essence, 2 Soul Dust", "Trainer", "Required rod upgrade." },
        { "156-185", "40x Enchant Bracer: Lesser Strength", "80 Soul Dust", "Limited vendor formula", "At 165, Bracer: Spirit can be cheaper if Lesser Mystic Essence is low." },
        { "185-200", "15x Enchant Bracer: Strength", "15 Vision Dust", "Trainer", "Start the Vision Dust stretch." },
        { "200-201", "1x Runed Truesilver Rod", "Truesilver Rod, Black Pearl, 2 Greater Mystic Essence, 2 Vision Dust", "Trainer", "Required rod upgrade." },
        { "201-220", "35x Enchant Bracer: Strength", "35 Vision Dust", "Trainer", "Yellow; buy enough dust for 30-35 casts." },
        { "220-225", "5x Enchant Cloak: Greater Defense", "15 Vision Dust", "Trainer", "Go to Annora in Uldaman for Artisan after this." },
        { "225-230", "5x Enchant Gloves: Agility", "5 Lesser Nether Essence, 5 Vision Dust", "Annora", "Cloak: Greater Defense is an alternative." },
        { "230-235", "5x Enchant Boots: Stamina", "25 Vision Dust", "Annora", "Learn everything from Annora before leaving Uldaman." },
        { "235-250", "25x Enchant Chest: Superior Health", "150 Vision Dust", "Annora", "Formula: Bracer - Greater Stamina is a strong drop alternative." },
        { "250-265", "20x Lesser Mana Oil", "60 Dream Dust, 40 Purple Lotus, 20 Crystal Vial", "Kania in Silithus", "If unavailable in your phase, use Bracer: Greater Strength." },
        { "265-294", "30x Enchant Shield: Greater Stamina", "300 Dream Dust", "Limited BoP vendor formula", "Sold by Daniel Bartlett in Undercity and Mythrin'dir in Darnassus." },
        { "294-295", "1x Runed Arcanite Rod", "Arcanite Rod, Golden Pearl, 10 Illusion Dust, 4 Greater Eternal Essence, 4 Small Brilliant Shard, 2 Large Brilliant Shard", "Lorelae Wintersong", "Buy this and Cloak: Superior Defense in Moonglade." },
        { "295-300", "5x Enchant Cloak: Superior Defense", "40 Illusion Dust", "Lorelae Wintersong", "Shield: Greater Stamina can continue if Dream Dust is cheaper." },
    },
})

ns.addGuide({
    key = "engineering", name = "Engineering", kind = "Primary crafting",
    summary = "WoW-Professions Classic component-first route through bombs, mithril parts, and thorium.",
    tips = {
        "Buy a Blacksmith Hammer before starting.",
        "Save powders, bolts, gizmos, frameworks, triggers, casings, and selected tubes until the route consumes them.",
        "Gnome characters have +15 Engineering, so they can often stay on cheaper recipes longer.",
    },
    shopping = {
        "60 Rough Stone, 60 Coarse Stone, 30 Heavy Stone, 120 Solid Stone, 60 Dense Stone",
        "66 Copper Bar, 5 Silver Bar, 110 Bronze Bar, 4 Steel Bar",
        "170 Mithril Bar, 225 Thorium Bar",
        "30 Linen Cloth, 60 Wool Cloth, 20 Mageweave Cloth, 35 Runecloth",
        "15 Medium Leather, 25 Weak Flux, 10 Moss Agate or extra Heavy Stone",
    },
    steps = {
        { "1-30", "60x Rough Blasting Powder", "60 Rough Stone", "Trainer", "Keep all powder for Rough Copper Bombs." },
        { "30-50", "30x Handful of Copper Bolts", "30 Copper Bar", "Trainer", "Keep around 30 for later." },
        { "50-51", "1x Arclight Spanner", "6 Copper Bar", "Trainer", "Required engineering tool." },
        { "51-75", "30x Rough Copper Bomb", "30 Copper Bar, 30 Copper Bolts, 60 Rough Blasting Powder, 30 Linen Cloth", "Trainer", "Train Journeyman before the 75 cap." },
        { "75-90", "60x Coarse Blasting Powder", "60 Coarse Stone", "Trainer", "Keep the powder." },
        { "90-100", "20x Coarse Dynamite", "60 Coarse Blasting Powder, 20 Linen Cloth", "Trainer", "Uses the powder just made." },
        { "100-105", "5x Silver Contact", "5 Silver Bar", "Trainer", "Alternative: Flying Tiger Goggles if Silver is expensive." },
        { "105-125", "25x Bronze Tube", "50 Bronze Bar, 25 Weak Flux", "Trainer", "Weak Flux is sold by Engineering Supply vendors." },
        { "125-135", "10x Standard Scope", "10 Bronze Tube, 10 Moss Agate", "Trainer", "Use Heavy Blasting Powder if Moss Agate is expensive." },
        { "135-150", "Heavy Blasting Powder and Whirring Bronze Gizmo", "30 Heavy Stone, 30 Bronze Bar, 15 Wool Cloth", "Trainer", "Make 30 powder and 15 gizmos; keep both." },
        { "150-160", "15x Bronze Framework", "30 Bronze Bar, 15 Medium Leather, 15 Wool Cloth", "Trainer", "Keep the frameworks." },
        { "160-175", "15x Explosive Sheep", "30 Heavy Blasting Powder, 15 Whirring Bronze Gizmo, 15 Bronze Framework, 30 Wool Cloth", "Trainer", "Keep 5 if you choose Goblin Engineering." },
        { "175-194", "60x Solid Blasting Powder", "120 Solid Stone", "Trainer", "Save these for Mithril crafts." },
        { "194-195", "1x Gyromatic Micro-Adjustor", "4 Steel Bar", "Trainer", "Required engineering tool." },
        { "195-200", "7x Mithril Tube", "21 Mithril Bar", "Trainer", "Keep 6 if you choose Gnomish Engineering." },
        { "200-215", "20x Unstable Trigger", "20 Mithril Bar, 20 Mageweave Cloth, 20 Solid Blasting Powder", "Trainer", "Save the triggers." },
        { "215-238", "40x Mithril Casing", "120 Mithril Bar", "Trainer", "Save the casings." },
        { "238-250", "20x Hi-Explosive Bomb", "40 Mithril Casing, 20 Unstable Trigger, 40 Solid Blasting Powder", "Trainer", "Consumes the saved components." },
        { "250-260", "30x Dense Blasting Powder", "60 Dense Stone", "Trainer", "May require extras to reach 260." },
        { "260-285", "35x Thorium Widget", "105 Thorium Bar, 35 Runecloth", "Vendor recipe", "Recipe sold by Gearcutter Cogspinner in Ironforge and Sovik in Orgrimmar." },
        { "285-300", "20x Thorium Tube", "120 Thorium Bar", "Vendor schematic", "Schematic sold by Xizzer Fizzbolt in Everlook." },
    },
})
