local _, ns = ...

ns.addGuide({
    key = "leatherworking", name = "Leatherworking", kind = "Primary crafting",
    summary = "WoW-Professions Classic Skinning-friendly route through Light, Medium, Heavy, Thick, and Rugged Leather.",
    tips = {
        "Leatherworking is easiest to level with Skinning.",
        "Make Cured Medium Hide and Cured Heavy Hide when you have cheap hides; later recipes can use them.",
        "The 260-300 section has useful alternatives if Runecloth, Black Dye, or Rugged Leather prices shift.",
    },
    shopping = {
        "57 Ruined Leather Scraps, 470 Light Leather, 335 Medium Leather",
        "20 Heavy Hide, 195 Heavy Leather, 650 Thick Leather",
        "400 Rugged Leather, 100 Runecloth",
        "Coarse Thread, Fine Thread, Silken Thread, Heavy Silken Thread, Rune Thread",
        "60 Salt, 35 Gray Dye, 33 Black Dye",
    },
    steps = {
        { "1-20", "19x Light Leather", "57 Ruined Leather Scraps", "Trainer", "Make the armor kit opener instead if you do not have scraps." },
        { "20-45", "40x Light Armor Kit", "40 Light Leather", "Trainer", "If starting without scraps, use this from 1-45." },
        { "45-55", "20x Handstitched Leather Cloak", "40 Light Leather, 20 Coarse Thread", "Trainer", "Train Journeyman after this." },
        { "55-100", "50x Embossed Leather Gloves", "150 Light Leather, 100 Coarse Thread", "Trainer", "Main Light Leather sink." },
        { "100-125", "40x Fine Leather Belt", "240 Light Leather, 80 Coarse Thread", "Trainer", "Make Cured Medium Hide too if Medium Hide is cheap." },
        { "125-137", "15x Dark Leather Boots", "60 Medium Leather, 30 Fine Thread, 15 Gray Dye", "Trainer", "Dark Leather Belt is useful if you made Cured Medium Hide." },
        { "137-150", "20x Dark Leather Pants", "240 Medium Leather, 20 Gray Dye, 20 Fine Thread", "Trainer", "Train Expert before 150." },
        { "150-155", "7x Heavy Leather or 7x Heavy Leather Ball", "35 Medium Leather or 14 Heavy Leather, 7 Fine Thread", "Trainer", "Use the cheaper option for your bags/AH." },
        { "155-165", "20x Cured Heavy Hide", "20 Heavy Hide, 60 Salt", "Trainer", "Keep these; later recipes consume them." },
        { "165-180", "15x Heavy Armor Kit", "75 Heavy Leather, 15 Fine Thread", "Trainer", "Alternate route can continue Heavy Armor Kits from 155." },
        { "180-190", "10x Barbaric Shoulders", "80 Heavy Leather, 10 Cured Heavy Hide, 20 Fine Thread", "Trainer", "Uses the hides saved earlier." },
        { "190-200", "10x Guardian Gloves", "40 Heavy Leather, 10 Cured Heavy Hide, 10 Silken Thread", "Trainer", "Final Heavy Leather stretch." },
        { "200-205", "5x Thick Armor Kit", "25 Thick Leather, 5 Silken Thread", "Trainer", "Visit the Artisan trainer after 205." },
        { "205-235", "40x Nightscape Headband", "200 Thick Leather, 80 Silken Thread", "Artisan trainer", "Horde learns Artisan from Hahrana Ironhide; Alliance from Drakk Stonehand." },
        { "235-250", "15x Nightscape Pants", "210 Thick Leather, 60 Silken Thread", "Artisan trainer", "Efficient Thick Leather step." },
        { "250-260", "13x Nightscape Boots", "208 Thick Leather, 26 Heavy Silken Thread", "Trainer", "Bridge into Rugged Leather recipes." },
        { "260-290", "33x Wicked Leather Gauntlets", "264 Rugged Leather, 33 Black Dye, 33 Rune Thread", "Trainer", "Alternative: 28x Wicked Leather Bracers with 224 Rugged Leather, 28 Black Dye, 28 Rune Thread." },
        { "290-300", "10x Runic Leather Headband", "140 Rugged Leather, 100 Runecloth, 10 Rune Thread", "Trainer", "Alternatives include Wicked Leather Headband, Runic Leather Belt, Bracers, or Gauntlets." },
    },
})

ns.addGuide({
    key = "tailoring", name = "Tailoring", kind = "Primary crafting",
    summary = "WoW-Professions Classic cloth route through Linen, Wool, Silk, Mageweave, and Runecloth.",
    tips = {
        "Tailoring does not require a gathering profession; humanoid farming and dungeon cloth drops fuel it.",
        "Enchanting pairs well because many crafted greens can be disenchanted.",
        "Only make bolts as the route calls for them unless you already know your final recipes.",
    },
    shopping = {
        "204 Linen Cloth, 135 Wool Cloth, 804 Silk Cloth",
        "470 Mageweave Cloth, 1195 Runecloth, 110 Rugged Leather",
        "Coarse Thread, Fine Thread, Silken Thread, Heavy Silken Thread, Rune Thread",
        "Blue Dye, Red Dye, Orange Dye, Bleach",
    },
    steps = {
        { "1-45", "102x Bolt of Linen Cloth", "204 Linen Cloth", "Trainer", "You will use many of these immediately." },
        { "40-70", "40x Linen Belt", "40 Bolt of Linen Cloth, 40 Coarse Thread", "Trainer", "Start at 40 when the recipe unlocks." },
        { "70-75", "5x Reinforced Linen Cape", "10 Bolt of Linen Cloth, 15 Coarse Thread", "Trainer", "Train Journeyman after this." },
        { "75-100", "45x Bolt of Woolen Cloth", "135 Wool Cloth", "Trainer", "Prepare Wool bolts." },
        { "100-110", "13x Simple Kilt", "52 Bolt of Linen Cloth, 13 Fine Thread", "Trainer", "Uses remaining Linen bolts." },
        { "110-125", "15x Double-stitched Woolen Shoulders", "45 Bolt of Woolen Cloth, 30 Fine Thread", "Trainer", "Train Expert at 125." },
        { "125-145", "201x Bolt of Silk Cloth", "804 Silk Cloth", "Expert trainer", "Expert trainers are Josef Gregorian and Georgio Bolero." },
        { "145-160", "18x Azure Silk Hood", "36 Bolt of Silk Cloth, 36 Blue Dye, 18 Fine Thread", "Trainer", "First Silk gear step." },
        { "160-170", "10x Silk Headband", "30 Bolt of Silk Cloth, 20 Fine Thread", "Trainer", "Efficient Silk step." },
        { "170-175", "5x Formal White Shirt", "15 Bolt of Silk Cloth, 10 Bleach, 5 Fine Thread", "Trainer", "Short bridge to Mageweave." },
        { "175-185", "94x Bolt of Mageweave", "470 Mageweave Cloth", "Trainer", "Prepare Mageweave bolts." },
        { "185-205", "20x Crimson Silk Vest", "80 Bolt of Silk Cloth, 40 Fine Thread, 40 Red Dye", "Trainer", "Uses saved Silk bolts." },
        { "205-215", "10x Crimson Silk Pantaloons", "40 Bolt of Silk Cloth, 20 Red Dye, 20 Silken Thread", "Trainer", "Continue Silk gear." },
        { "215-220", "5x Orange Mageweave Shirt", "5 Bolt of Mageweave, 5 Orange Dye, 5 Heavy Silken Thread", "Trainer", "Train Artisan after this." },
        { "220-230", "10x Black Mageweave Gloves", "20 Bolt of Mageweave, 20 Heavy Silken Thread", "Artisan trainer", "Artisan trainers are Daryl Stack and Timothy Worthington." },
        { "230-250", "23x Black Mageweave Headband", "69 Bolt of Mageweave, 46 Heavy Silken Thread", "Trainer", "Main Black Mageweave stretch." },
        { "250-260", "239x Bolt of Runecloth", "1195 Runecloth", "Trainer", "Prepare Runecloth bolts for the final recipes." },
        { "260-280", "25x Runecloth Belt", "75 Bolt of Runecloth, 25 Rune Thread", "Trainer", "Continue belts to 290 if Runecloth Bag materials are high." },
        { "280-290", "18x Runecloth Bag", "90 Bolt of Runecloth, 36 Rugged Leather, 18 Rune Thread", "Trainer", "Alternative: 8 more Runecloth Belts to 290." },
        { "290-300", "18x Runecloth Gloves", "72 Bolt of Runecloth, 72 Rugged Leather, 18 Rune Thread", "Trainer", "Alternatives include Brightcloth Cloak/Gloves/Robe or Runecloth Pants if cheaper." },
    },
})
